# 行列とベクトル　ベクトルと行列の計算01
* 以下に示す式を計算しベクトルyを返す関数test()を実装せよ
* ここで、ひな形におけるcはfloat型，Aはmatrix型，xは1次元のndarray型，test()が返す型はmatrix型とする(yを縦ベクトルとみなす）
* （任意）ベクトルのサイズと行列のサイズが合わないために解が存在しない場合はNoneを返せ


\begin{equation*}
\vec{y}=cA\vec{x}
\end{equation*}

In [5]:
# ひな形
import numpy as np

def test(c, A, x):
    y = "ひな形"
    return y

def main():
    # サンプルのパラメータ（型は問題文の指定による）
    c = 3.55
    a = np.matrix(
           [[ 0.05396288,  0.261556,    0.16012637],
            [ 0.08309702,  0.80172185,  0.13203421],
            [ 0.69138189,  0.53467751,  0.93737161]])
    x = np.array([1, 2, 3])

    print(test(c, a, x))     # testの呼び出しと、結果の表示
    # mainを実行した結果、以下の様に表示されればよい
    #[[  3.75396166]
    #[  7.39338389]
    #[ 16.23362368]]
        
if __name__ == "__main__":    # スクリプトファイルとして実行した際に、main()を実行させる
    main()

ひな形


In [13]:
# 解答例
import copy
import numpy as np

def test(c, A, x):
    # サイズのチェックで、計算可能か判断する
    h, w = A.shape
    if len(x) != h:
        return None
    
    # 計算
    x = np.matrix(x)      # 型の変換。1D ndarray -> matrix
    x = x.T                      # 転置して、縦ベクトルに変換
    y = c * A * x             # 指定されている計算の実施
    #print(type(y), y)     # 型のチェックと中身の表示。確認後はコメントアウト
    return y


def main():
    # サンプルのパラメータ（型は問題文の指定による）
    c = 3.55
    a = np.matrix(
           [[ 0.05396288,  0.261556,    0.16012637],
            [ 0.08309702,  0.80172185,  0.13203421],
            [ 0.69138189,  0.53467751,  0.93737161]])
    x = np.array([1, 2, 3])
    
    print(test(c, a, x))     # testの呼び出しと、結果の表示
    # mainを実行した結果、以下の様に表示されればよい
    #[[  3.75396166]
    #[  7.39338389]
    #[ 16.23362368]]
    
if __name__ == "__main__":   # スクリプトファイルとして実行した際に、main()を実行させる
    main()

[[  3.75396166]
 [  7.39338389]
 [ 16.23362368]]
